Fixed bug#8214 - OTRS Init script on Red Hat fails to check scheduler.

diff --git a/scripts/redhat-rcotrs b/scripts/redhat-rcotrs
--- a/scripts/redhat-rcotrs
+++ b/scripts/redhat-rcotrs
@@ -45,8 +45,8 @@ if ! test -r $OTRS_CHECKDB; then
     exit 5
 fi
 
-if ! test -r $OTRS_CHECKSCHEDULER; then
-    echo "Error: $OTRS_CHECKSCHEDULER not found!"
+if ! test -r $OTRS_SCHEDULER; then
+    echo "Error: $OTRS_SCHEDULER not found!"
     exit 5
 fi
 
@@ -97,17 +97,21 @@ case "$1" in
       # --
       # OTRS Scheduler Service
       # --
-      echo -n " Checking OTRS Scheduler Service... "
-      $OTRS_SCHEDULER -a status |grep 'Running' > /dev/null 2>&1
-      TEST_STATUS=$?
-      echo $TEST_STATUS
-      if  test $TEST_STATUS -ne 0; then
-          echo " Error! "
-      echo "  This can happen if your database is not configured yet. "
-          exit 1;
-      else
-          echo " done."
-      fi  
+      if test $OTRS_SCHEDULER_RUNNING -gt 0; then
+          echo -n " Starting OTRS Scheduler Service... "
+          # check if scheduler is not running already
+          if ! $OTRS_SCHEDULER -a status -s 1 > /dev/null; then
+              if ! $OTRS_SCHEDULER -a start -s 1; then
+                  echo " Error! "
+                  echo "  This can happen if your database is not configured yet. "
+                  exit 1;
+              else
+                  echo " done."
+              fi
+          else
+              echo " was already running, done."
+          fi
+      fi
 
       # --
       # enable otrs.PostMaster.pl
@@ -250,15 +254,15 @@ case "$1" in
       # --
       # scheduler check
       # --
-      echo -n "Checking OTRS Scheduler service.... "
-      $OTRS_SCHEDULER -a status |grep 'Running' > /dev/null 2>&1
-      TEST_STATUS=$?
-      echo $TEST_STATUS
-      if  test $TEST_STATUS -ne 0; then
-          echo " Error! "
-          echo " Maybe your database isn't configured yet? "
-      else
-          echo "done."
+
+      if test $OTRS_SCHEDULER_RUNNING -gt 0; then
+          echo -n "Checking OTRS Scheduler service.... "
+          if ! $OTRS_SCHEDULER -a status -s 1; then
+              echo " Error! "
+              echo " Maybe your database isn't configured yet? "
+          else
+              echo "done."
+          fi
       fi
 
       # --
