added /etc/sysconfig/otrs as config file for rcscripts

diff --git a/scripts/redhat-rcotrs b/scripts/redhat-rcotrs
--- a/scripts/redhat-rcotrs
+++ b/scripts/redhat-rcotrs
@@ -12,50 +12,16 @@
 # description: Open Ticket Request System
 # config: /etc/sysconfig/otrs
 
+#
 # load the configuration
 #
-test -r /etc/sysconfig/otrs && . /etc/sysconfig/otrs
+if test -r /etc/sysconfig/otrs; then 
+    . /etc/sysconfig/otrs
+else
+    echo "ERROR: Can't find /etc/sysconfig/otrs!"
+    exit 5;
+fi
 
-
-# --- All this shit will go on /etc/sysconfig/otrs when i'll got
-# --- time and make another rpm.. (maybe on beta7? ;)) [pruiz@ip6seguridad.com]
- 
-# if one of this is false, it will not be checked at the startup!
-# Note: (may be the database isn't on the same host! --> DB_RUNNING=0) 
-# 
-OTRS_ROOT=/opt/OpenTRS
-DB_RUNNING=1
-HTTP_RUNNING=1
-CRON_RUNNING=1
-
-#
-# Used database [mysql|postgresql]
-# Note: Take care, that you have changed the Config.pm database settings!
-#
-
-HOST=`hostname -f`
-
-USED_DB=mysqld
-#USED_DB_TEST="ps --pid $(cat /var/lib/mysql/$HOST.pid)"
-USED_DB_TEST="/sbin/service mysqld status | grep 'is running'"
-# --- The Wonderfull redhat's mysql init script does not have a status check.. sucks
-#USED_DB=PostgreSQL
-#USED_DB_RCSCRIPT="service postgresql status| grep 'is running' > /dev/null 2>&1"
-
-USED_WEBSERVER=httpd   #Redhat's default httpd is apache..
-USED_WEBSERVER_TEST="/sbin/service httpd status | grep 'is running'"
-
-OTRS_POSTMASTER=$OTRS_ROOT/bin/PostMaster.pl
-OTRS_SPOOLDIR=$OTRS_ROOT/var/spool
-OTRS_CHECKDB=$OTRS_ROOT/bin/CheckDB.pl
-
-CRON_DIR=$OTRS_ROOT/var/cron
-CRON_TMP_FILE=$OTRS_ROOT/var/tmp/cron
-CRON_USER=" -u otrs "
-
-OTRS_HTTP_LOCATION="otrs"
-
-# --- END SHIT ;)
 # 
 # check needed files
 # 
@@ -73,9 +39,7 @@ if ! test -r $OTRS_CHECKDB; then
     echo "Error: $OTRS_CHECKDB not found!"
     exit 5
 fi
- 
 
-prog="OTRS"
 # 
 # main part
 # 
@@ -84,18 +48,18 @@ case "$1" in
     # start
     # ------------------------------------------------------
     start)
-      echo $"Starting $prog.."
+      echo $"Starting $OTRS_PROG.."
 
       # --
       # test if apache is running..
       # --
-      if test $HTTP_RUNNING -gt 0; then
+      if test $OTRS_HTTP_RUNNING -gt 0; then
 	echo -n " Checking httpd ..."	
-        if $USED_WEBSERVER_TEST >/dev/null 2>&1; then
+        if $OTRS_USED_WEBSERVER_TEST >/dev/null 2>&1; then
           echo " done."
         else
           echo "  failed!"
-          echo "  --> Please start the webserver at first! (service $USED_WEBSERVER start) <--"
+          echo "  --> Please start the webserver at first! (service $OTRS_USED_WEBSERVER start) <--"
           exit 1
         fi
       else
@@ -105,17 +69,17 @@ case "$1" in
       # --
       # check mysql, mysql init script does not have a status check...
       # --
-      if test $DB_RUNNING -gt 0; then
+      if test $OTRS_DB_RUNNING -gt 0; then
 	echo -n " Checking MySQL ..."
-        if $USED_DB_TEST >/dev/null 2>&1; then 
+        if $OTRS_USED_DB_TEST >/dev/null 2>&1; then 
           echo " done."
         else 
           echo " failed."
-          echo "  --> Please start the database at first! (service $USED_DB start) <--"
+          echo "  --> Please start the database at first! (service $OTRS_USED_DB start) <--"
           exit 1;
         fi
       else 
-          echo " Disabled: $USED_DB check!"
+          echo " Disabled: $OTRS_USED_DB check!"
       fi
 
       # --
@@ -128,7 +92,7 @@ case "$1" in
           echo ""
           echo " Try the web installer to configure your database: "
           echo ""
-          echo "     -->> http://$HOST/$OTRS_HTTP_LOCATION/installer.pl <<-- "
+          echo "     -->> http://$OTRS_HOST/$OTRS_HTTP_LOCATION/installer.pl <<-- "
           echo ""                               
           echo " or configure your database with README.database (DB - Setup Example)    "
           exit 1;
@@ -167,9 +131,9 @@ case "$1" in
       # --
       # Cron stuff
       # -- 
-      if test $CRON_RUNNING -gt 0; then
-	echo -e " Creating cronjobs (source $CRON_DIR/*) ..."
-        if mkdir -p $CRON_DIR; cat $CRON_DIR/* > $CRON_TMP_FILE && crontab $CRON_USER $CRON_TMP_FILE ; then
+      if test $OTRS_CRON_RUNNING -gt 0; then
+	echo -e " Creating cronjobs (source $OTRS_CRON_DIR/*) ..."
+        if mkdir -p $OTRS_CRON_DIR; cat $OTRS_CRON_DIR/* > $OTRS_CRON_TMP_FILE && crontab $OTRS_CRON_USER $OTRS_CRON_TMP_FILE ; then
           echo " done."
         else
           echo " failed!"
@@ -180,8 +144,8 @@ case "$1" in
       fi
  
       echo ""
-      echo "  -->> http://$HOST/$OTRS_HTTP_LOCATION/index.pl <<-- "
-      echo $"Final start of $prog.. done"
+      echo "  -->> http://$OTRS_HOST/$OTRS_HTTP_LOCATION/index.pl <<-- "
+      echo $"Final start of $OTRS_PROG.. done"
     ;;
     # ------------------------------------------------------
     # stop
@@ -201,9 +165,9 @@ case "$1" in
       # --
       # stop cron stuff
       # --
-      if test $CRON_RUNNING -gt 0; then
+      if test $OTRS_CRON_RUNNING -gt 0; then
         echo -e " Shutting down cronjobs ..."
-	if crontab $CRON_USER -r ; then
+	if crontab $OTRS_CRON_USER -r ; then
           echo " done."
         else
           echo " failed!"
@@ -213,7 +177,7 @@ case "$1" in
           echo " Disabled: cronjobs!"
       fi
 
-      echo $"Final shutdown of $prog.. done"
+      echo $"Final shutdown of $OTRS_PROG.. done"
     ;;
     # ------------------------------------------------------
     # restart
@@ -252,12 +216,12 @@ case "$1" in
       # --
       # httpd
       # --
-      /sbin/service $USED_WEBSERVER status
+      /sbin/service $OTRS_USED_WEBSERVER status
 
       # --
       # mysql
       # --
-      /sbin/service $USED_DB status
+      /sbin/service $OTRS_USED_DB status
       # --
       # db check
       # --
diff --git a/scripts/suse-rcotrs b/scripts/suse-rcotrs
--- a/scripts/suse-rcotrs
+++ b/scripts/suse-rcotrs
@@ -3,7 +3,7 @@
 # suse-rcotrs - rc script of otrs for SuSE Linux
 # Copyright (C) 2002 Martin Edenhofer <martin+code@otrs.org>
 # --
-# $Id: suse-rcotrs,v 1.17 2002-09-01 13:03:26 martin Exp $
+# $Id: suse-rcotrs,v 1.18 2002-09-23 14:43:40 martin Exp $
 # --
 # This software comes with ABSOLUTELY NO WARRANTY. For details, see 
 # the enclosed file COPYING for license information (GPL). If you 
@@ -27,6 +27,8 @@
 #
 test -r /etc/rc.config && . /etc/rc.config
 
+test -r /etc/rc.config.d/otrs && . /etc/rc.config.d/otrs
+
 test -r /etc/sysconfig/otrs && . /etc/sysconfig/otrs
 
 # Shell functions sourced from /etc/rc.status:
@@ -41,75 +43,28 @@ test -r /etc/sysconfig/otrs && . /etc/sysconfig/otrs
 test -s /etc/rc.status && . /etc/rc.status
 
 # 
-# if one of this is false, it will not be checked at the startup!
-# Note: (may be the database isn't on the same host! --> DB_RUNNING=0) 
-# 
-DB_RUNNING=1
-HTTP_RUNNING=1
-CRON_RUNNING=1
-
-# 
-# OTRS home (root) directory
-#
-OTRS_ROOT=/opt/OpenTRS
-
-# 
-# Used database [mysql|postgresql]
-# Note: Take care, that you have changed the Config.pm database settings!
-# 
-USED_DB=MySQL
-USED_DB_RCSCRIPT=rcmysql
-#USED_DB=PostgreSQL
-#USED_DB_RCSCRIPT=rcpostgresql
-
-#
-# Used webserver [apache]
-#
-USED_WEBSERVER=Apache
-USED_WEBSERVER_RCSCRIPT=rcapache
-
-#
-# cron stuff
-# 
-CRON_DIR=$OTRS_ROOT/var/cron
-CRON_TMP_FILE=$OTRS_ROOT/var/tmp/cron
-CRON_USER=" -u otrs "
-
-# 
 # check needed files
 # 
-OTRS_POSTMASTER=$OTRS_ROOT/bin/PostMaster.pl
+if ! test -r $OTRS_ROOT; then
+    echo "Error: $OTRS_ROOT not found!"
+    exit 5
+fi
+
 if ! test -r $OTRS_POSTMASTER; then
     echo "Error: $OTRS_POSTMASTER not found!"
     exit 5
 fi
 
-OTRS_SPOOLDIR=$OTRS_ROOT/var/spool
 if ! test -d $OTRS_SPOOLDIR; then
     echo "Error: $OTRS_SPOOLDIR not found!"
     exit 5
 fi
 
-OTRS_CHECKDB=$OTRS_ROOT/bin/CheckDB.pl
 if ! test -r $OTRS_CHECKDB; then
     echo "Error: $OTRS_CHECKDB not found!"
     exit 5
 fi
  
-
-# 
-# get host name
-#
-HOST=`hostname -f`
-# 
-# OTRS location - means http://host/$OTRS_HTTP_LOCATION/index.pl
-# 
-OTRS_HTTP_LOCATION="otrs"
-# 
-# program name
-# 
-PROG="OTRS"
-
 # reset status of this service
 rc_reset
 
@@ -126,18 +81,18 @@ case "$1" in
     # start
     # ------------------------------------------------------
     start)
-      echo "Starting $PROG"
+      echo "Starting $OTRS_PROG"
 
       # --
       # start webserver
       # --
-      if test $HTTP_RUNNING -gt 0; then
-        if $USED_WEBSERVER_RCSCRIPT status > /dev/null 2>&1 ; then
-          echo " Checking $USED_WEBSERVER ... done."
+      if test $OTRS_HTTP_RUNNING -gt 0; then
+        if $OTRS_USED_WEBSERVER_RCSCRIPT status > /dev/null 2>&1 ; then
+          echo " Checking $OTRS_USED_WEBSERVER ... done."
           rc_status
         else
-          echo " Checking $USED_WEBSERVER ... failed!"
-          echo "  --> Please start the webserver at first! ($USED_WEBSERVER_RCSCRIPT start) <--"
+          echo " Checking $OTRS_USED_WEBSERVER ... failed!"
+          echo "  --> Please start the webserver at first! ($OTRS_USED_WEBSERVER_RCSCRIPT start) <--"
           rc_failed
           exit 1
         fi
@@ -148,13 +103,13 @@ case "$1" in
       # --
       # check database
       # --
-      if test $DB_RUNNING -gt 0; then
-        if $USED_DB_RCSCRIPT status > /dev/null 2>&1 ; then 
-          echo " Checking $USED_DB ... done."
+      if test $OTRS_DB_RUNNING -gt 0; then
+        if $OTRS_USED_DB_RCSCRIPT status > /dev/null 2>&1 ; then 
+          echo " Checking $OTRS_USED_DB ... done."
           rc_status 
         else 
-          echo " Checking $USED_DB ... failed."
-          echo "  --> Please start the database at first! ($USED_DB_RCSCRIPT start) <--"
+          echo " Checking $OTRS_USED_DB ... failed."
+          echo "  --> Please start the database at first! ($OTRS_USED_DB_RCSCRIPT start) <--"
           rc_failed
           rc_status -v 
           exit 1;
@@ -177,7 +132,7 @@ case "$1" in
           echo " Try the web installer to configure your database: "
           echo ""
           echo ""
-          echo "     -->> http://$HOST/$OTRS_HTTP_LOCATION/installer.pl <<-- "
+          echo "     -->> http://$OTRS_HOST/$OTRS_HTTP_LOCATION/installer.pl <<-- "
           echo ""                               
           echo ""
           echo "----------------------------------------------------------------------------"
@@ -221,12 +176,12 @@ case "$1" in
       # --
       # start cron stuff
       # --
-      if test $CRON_RUNNING -gt 0; then
-        if mkdir -p $CRON_DIR; cat $CRON_DIR/* > $CRON_TMP_FILE && crontab $CRON_USER $CRON_TMP_FILE ; then
-          echo " Creating cronjobs (source $CRON_DIR/*) ... done."
+      if test $OTRS_CRON_RUNNING -gt 0; then
+        if mkdir -p $OTRS_CRON_DIR; cat $OTRS_CRON_DIR/* > $OTRS_CRON_TMP_FILE && crontab $OTRS_CRON_USER $OTRS_CRON_TMP_FILE ; then
+          echo " Creating cronjobs (source $OTRS_CRON_DIR/*) ... done."
           rc_status
         else
-          echo " Creating cronjobs (source $CRON_DIR/*) ... failed!"
+          echo " Creating cronjobs (source $OTRS_CRON_DIR/*) ... failed!"
           rc_failed
           exit 1
         fi
@@ -235,7 +190,7 @@ case "$1" in
       fi
 
       echo ""
-      echo "  -->> http://$HOST/$OTRS_HTTP_LOCATION/index.pl <<-- "
+      echo "  -->> http://$OTRS_HOST/$OTRS_HTTP_LOCATION/index.pl <<-- "
 
       # show status
       rc_status -v
@@ -244,7 +199,7 @@ case "$1" in
     # stop
     # ------------------------------------------------------
     stop)
-      echo "Shutting down $PROG "
+      echo "Shutting down $OTRS_PROG "
 
       # --
       # disable PostMaster.pl
@@ -260,8 +215,8 @@ case "$1" in
       # --
       # stop cron stuff
       # --
-      if test $CRON_RUNNING -gt 0; then
-        if crontab $CRON_USER -r ; then
+      if test $OTRS_CRON_RUNNING -gt 0; then
+        if crontab $OTRS_CRON_USER -r ; then
           echo " Shutting down cronjobs ... done."
           rc_status
         else
@@ -281,17 +236,17 @@ case "$1" in
     # start-force
     # ------------------------------------------------------
     start-force)
-      echo "Starting $PROG (completely)"
+      echo "Starting $OTRS_PROG (completely)"
 
       # --
       # start webserver
       # --
-      if test $HTTP_RUNNING -gt 0; then
-        if $USED_WEBSERVER_RCSCRIPT restart > /dev/null 2>&1 ; then
-          echo " Starting $USED_WEBSERVER ... done."
+      if test $OTRS_HTTP_RUNNING -gt 0; then
+        if $OTRS_USED_WEBSERVER_RCSCRIPT restart > /dev/null 2>&1 ; then
+          echo " Starting $OTRS_USED_WEBSERVER ... done."
           rc_status
         else
-          echo " Starting $USED_WEBSERVER ... failed!"
+          echo " Starting $OTRS_USED_WEBSERVER ... failed!"
           rc_failed
           exit 1
         fi
@@ -302,14 +257,14 @@ case "$1" in
       # --
       # check database
       # --
-      if test $DB_RUNNING -gt 0; then
-        if $USED_DB_RCSCRIPT restart > /dev/null 2>&1 ; then 
+      if test $OTRS_DB_RUNNING -gt 0; then
+        if $OTRS_USED_DB_RCSCRIPT restart > /dev/null 2>&1 ; then 
           # just in case, some databases can't get ready so fast!
           sleep 5;
-          echo " Starting $USED_DB ... done."
+          echo " Starting $OTRS_USED_DB ... done."
           rc_status 
         else 
-          echo " Starting $USED_DB ... failed."
+          echo " Starting $OTRS_USED_DB ... failed."
           rc_failed
           rc_status -v 
           exit 1;
@@ -338,17 +293,17 @@ case "$1" in
       # --
       # stop force
       # --
-      echo "Shutting down $PROG (completely)"
+      echo "Shutting down $OTRS_PROG (completely)"
 
       # --
       # webserver
       # --
-      if test $HTTP_RUNNING -gt 0; then
-        if $USED_WEBSERVER_RCSCRIPT stop > /dev/null 2>&1 ; then
-          echo " Shutting down $USED_WEBSERVER ... done."
+      if test $OTRS_HTTP_RUNNING -gt 0; then
+        if $OTRS_USED_WEBSERVER_RCSCRIPT stop > /dev/null 2>&1 ; then
+          echo " Shutting down $OTRS_USED_WEBSERVER ... done."
           rc_status 
         else
-          echo " Shutting down $USED_WEBSERVER ... failed."
+          echo " Shutting down $OTRS_USED_WEBSERVER ... failed."
           rc_failed
         fi
       fi
@@ -356,12 +311,12 @@ case "$1" in
       # --
       # database
       # --
-      if test $DB_RUNNING -gt 0; then
-        if $USED_DB_RCSCRIPT stop > /dev/null 2>&1 ; then
-          echo " Shutting down $USED_DB ... done."
+      if test $OTRS_DB_RUNNING -gt 0; then
+        if $OTRS_USED_DB_RCSCRIPT stop > /dev/null 2>&1 ; then
+          echo " Shutting down $OTRS_USED_DB ... done."
           rc_status 
         else
-          echo " Shutting down $USED_DB ... failed."
+          echo " Shutting down $OTRS_USED_DB ... failed."
           rc_failed
         fi
       fi
@@ -416,12 +371,12 @@ case "$1" in
       # --
       # webserver
       # --
-      $USED_WEBSERVER_RCSCRIPT status
+      $OTRS_USED_WEBSERVER_RCSCRIPT status
 
       # --
       # database
       # --
-      $USED_DB_RCSCRIPT status
+      $OTRS_USED_DB_RCSCRIPT status
 
       # --
       # db check
