Added check to OTRS Scheduler before start to know if it was already started.

diff --git a/scripts/suse-rcotrs b/scripts/suse-rcotrs
--- a/scripts/suse-rcotrs
+++ b/scripts/suse-rcotrs
@@ -3,7 +3,7 @@
 # suse-rcotrs - rc script of otrs for SUSE Linux
 # Copyright (C) 2001-2012 OTRS AG, http://otrs.org/
 # --
-# $Id: suse-rcotrs,v 1.36 2012-06-11 16:10:10 mb Exp $
+# $Id: suse-rcotrs,v 1.37 2012-06-11 23:19:27 cr Exp $
 # --
 # This software comes with ABSOLUTELY NO WARRANTY. For details, see
 # the enclosed file COPYING for license information (AGPL). If you
@@ -161,14 +161,19 @@ case "$1" in
       # --
       if test $OTRS_SCHEDULER_RUNNING -gt 0; then
           echo -n " Starting OTRS Scheduler Service... "
-          if ! $OTRS_SCHEDULER -a start -s 1; then
-              echo " Error! "
-              echo "  This can happen if your database is not configured yet. "
-              exit 1;
+          # check if scheduler is not running already
+          if ! $OTRS_SCHEDULER -a status -s 1 > /dev/null; then
+              if ! $OTRS_SCHEDULER -a start -s 1; then
+                  echo " Error! "
+                  echo "  This can happen if your database is not configured yet. "
+                  exit 1;
+              else
+                  echo " done."
+              fi
           else
-              echo " done."
+              echo " was already running, done."
           fi
-      fi  
+      fi
 
       # --
       # enable otrs.PostMaster.pl
@@ -214,7 +219,7 @@ case "$1" in
       else
           echo " Disabled: cronjobs!"
       fi
-      
+
       echo ""
       echo "  -->> http://$OTRS_HOST/$OTRS_HTTP_LOCATION/index.pl <<-- "
 
@@ -418,7 +423,7 @@ case "$1" in
       # --
       # scheduler check
       # --
-      
+
       if test $OTRS_SCHEDULER_RUNNING -gt 0; then
           echo -n "Checking OTRS Scheduler service.... "
           if ! $OTRS_SCHEDULER -a status -s 1; then
