added check for needed variables

diff --git a/scripts/suse-rcotrs b/scripts/suse-rcotrs
--- a/scripts/suse-rcotrs
+++ b/scripts/suse-rcotrs
@@ -3,7 +3,7 @@
 # suse-rcotrs - rc script of otrs for SuSE Linux
 # Copyright (C) 2002 Martin Edenhofer <martin+code@otrs.org>
 # --
-# $Id: suse-rcotrs,v 1.19 2002-10-18 16:07:43 martin Exp $
+# $Id: suse-rcotrs,v 1.20 2002-10-20 19:52:08 martin Exp $
 # --
 # This software comes with ABSOLUTELY NO WARRANTY. For details, see 
 # the enclosed file COPYING for license information (GPL). If you 
@@ -25,11 +25,12 @@
 #
 # load the configuration
 #
+CONFIGFILE="rcconfig file not found!"
 test -r /etc/rc.config && . /etc/rc.config
 
-test -r /etc/rc.config.d/otrs && . /etc/rc.config.d/otrs
+test -r /etc/rc.config.d/otrs && . /etc/rc.config.d/otrs && CONFIGFILE=/etc/rc.config.d/otrs
 
-test -r /etc/sysconfig/otrs && . /etc/sysconfig/otrs
+test -r /etc/sysconfig/otrs && . /etc/sysconfig/otrs && CONFIGFILE=/etc/sysconfig/otrs
 
 # Shell functions sourced from /etc/rc.status:
 #      rc_check         check and set local and overall rc status
@@ -42,6 +43,21 @@ test -r /etc/sysconfig/otrs && . /etc/sysconfig/otrs
 #      rc_exit          exit appropriate to overall rc status
 test -s /etc/rc.status && . /etc/rc.status
 
+# 
+# check needed variable
+# 
+if ! test $OTRS_ROOT; then
+    echo "Error: Corrupt config file ($CONFIGFILE)! OTRS_ROOT not found!"
+    exit 5
+fi
+if ! test $OTRS_POSTMASTER; then
+    echo "Error: Corrupt config file ($CONFIGFILE)! OTRS_POSTMASTER not found!"
+    exit 5
+fi
+if ! test $OTRS_SPOOLDIR; then
+    echo "Error: Corrupt config file ($CONFIGFILE)! OTRS_SPOOLDIR not found!"
+    exit 5
+fi
 # 
 # check needed files
 # 
