bin/SetPermissions.sh

diff --git a/scripts/suse-rcotrs b/scripts/suse-rcotrs
--- a/scripts/suse-rcotrs
+++ b/scripts/suse-rcotrs
@@ -2,7 +2,7 @@
 # suse-rcotrs - rc script of otrs for SuSE Linux
 # Copyright (C) 2002 Martin Edenhofer <martin+code@otrs.org>
 # --
-# $Id: suse-rcotrs,v 1.3 2002-01-16 22:53:19 martin Exp $
+# $Id: suse-rcotrs,v 1.4 2002-02-03 22:48:20 martin Exp $
 # --
 # This software comes with ABSOLUTELY NO WARRANTY. For details, see 
 # the enclosed file COPYING for license information (GPL). If you 
@@ -44,24 +44,12 @@ test "$START_OTRS" = yes || exit 0
 # if one of this is false, it will not be checked at the startup!
 # Note: (may be the database isn't on the same host! --> DB_RUNNING=0) 
 # 
-DB_RUNNING=0
+DB_RUNNING=1
 HTTP_RUNNING=1
 
 # 
 # check needed files
 # 
-HTTPD_BIN=/usr/sbin/httpd
-if ! test -x $HTTPD_BIN ; then
-    echo "Error: $HTTPD_BIN not fount!"
-    exit 5
-fi
-
-OTRS_HTTPD_CONF=/opt/OpenTRS/scripts/suse-httpd.conf
-if ! test -r $OTRS_HTTPD_CONF ; then
-    echo "Error: $OTRS_HTTPD_CONF not fount!"
-    exit 5
-fi
-
 OTRS_POSTMASTER=/opt/OpenTRS/bin/PostMaster.pl
 if ! test -r $OTRS_POSTMASTER; then
     echo "Error: $OTRS_POSTMASTER not fount!"
@@ -91,6 +79,23 @@ case "$1" in
       echo "Starting OpenTRS"
 
       # --
+      # start apache
+      # --
+      if test $HTTP_RUNNING -gt 0; then
+        if rcapache restart > /dev/null 2>&1 ; then
+          echo " Starting httpd ... done."
+          rc_status
+        else
+          echo " Starting httpd ... faild."
+          rc_failed
+          exit 1
+        fi
+      else
+          echo " Disabled: httpd check!"
+      fi
+
+
+      # --
       # check mysql
       # --
       if test $DB_RUNNING -gt 0; then
@@ -113,6 +118,10 @@ case "$1" in
       echo -n " Checking database connect... ("
       if ! /opt/OpenTRS/bin/CheckDB.pl ; then
           echo ") Error!!"
+          echo "----------------------------------------------------------------------------"
+          echo "May the database isn't configured yet? Try http://yourhost/otrs/installer.pl"
+          echo "             or configure your database with README.database"
+          echo "----------------------------------------------------------------------------"
           rc_failed 
           rc_status -v
           exit 1;
@@ -137,24 +146,6 @@ case "$1" in
       echo " done."
       rc_status
 
-      # --
-      # check apache
-      # --
-      if test $HTTP_RUNNING -gt 0; then 
-        # stop old apache daemons
-        rcapache stop 2>&1 > /dev/null
-        if  $HTTPD_BIN -f $OTRS_HTTPD_CONF ; then
-          echo " Starting httpd ... done."
-          rc_status 
-        else 
-          echo " Starting httpd ... faild."
-          rc_failed
-          exit 1
-        fi
-      else 
-          echo " Disabled: httpd check!"
-      fi
-      
       # show status
       rc_status -v
     ;;
